##First read in the arguments listed at the command line
args=(commandArgs(TRUE))

##args is now a list of character vectors
## First check to see if arguments are passed.
## Then cycle through each element of the list and evaluate the expressions.
if(length(args)==0){
  print("No arguments supplied.")
  ##supply default values

}else{
  for(i in 1:length(args)){
    eval(parse(text=args[[i]]))
  }
}

library(rCASC)


separator <- ifelse(separator == "TAB", "\t", ",")

#clusterNgriph(group=group,scratch.folder=scratch.folder,file=file,nPerm=nPerm,permAtTime=permAtTime,percent=percent,separator=separator,logTen=logTen,seed=seed)
# cluster.path <- paste(data.folder=dirname(file), "Results", strsplit(basename(file),"\\.")[[1]][1], sep="/")
#  cluster <- as.numeric(list.dirs(cluster.path, full.names = FALSE, recursive = FALSE))
#  if(length(cluster)==1){
#permAnalysisGriph(group=group, scratch.folder=scratch.folder, file=file,cluster,separator,sp=0.8)
#} else{
#    cat("\nIt seems that there is more than one cluster folders in the output of griphPermutation\n")
#    cat("Check the results generated by griphPermutation, and run griphAnalysis selecting the cluster of interest\n")
#    system("echo 5 > ExitStatusFile 2>&1")
#    return(5)
#}

griphBootstrap(group=group, scratch.folder=scratch.folder, file=file, nPerm=nPerm, permAtTime=permAtTime, percent=percent, separator=separator, logTen=0, seed=seed)
